version: "3"

services:
    web:
        image: dockerized-app
        env_file:
            - ./docker.env
        ports:
            - "8093:80"
        command: /bin/bash -c "envsubst '$$BASE_URL' < /usr/share/nginx/html/assets/settings.json.template > /usr/share/nginx/html/assets/settings.json && exec nginx -g 'daemon off;'"
